# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: store
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./document/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data: